[package]

name = "iotop_server"
version = "0.0.1"
authors = [ "Piotr Pawłow <pp@siedziba.pl>" ]

[dependencies]
regex = "0.1.8"
time = "0.1"
rustc-serialize = "0.3.15"
websocket = "~0.12.1"
getopts = "0.2"

